#!/usr/bin/env python

import unittest

import roslaunch
import rospy
import std_msgs.msg


class TestBridge(unittest.TestCase):
    """Test peer to peer bridging."""

    def setUp(self):
        rospy.init_node("test_bridge")

        # We are in the primary roslaunch, start the secondary roslaunch
        uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)
        args = ["mule_bridge", "test_bridge.test", "primary:=false"]
        file_arg1 = roslaunch.rlutil.resolve_launch_arguments(args)[0]
        file_arg2 = args[2:]
        self._launch = roslaunch.parent.ROSLaunchParent(
            uuid,
            [(file_arg1, file_arg2)],
            is_core=True,
            port=roslaunch.DEFAULT_MASTER_PORT + 1,
        )
        self._launch.start()

    def tearDown(self):
        self._launch.shutdown()

    def test_roundtrip(self):
        expected = std_msgs.msg.String()
        expected.data = "Hello World"
        actual = rospy.wait_for_message("/test_volatile", std_msgs.msg.String)
        self.assertEqual(actual, expected)


if __name__ == "__main__":
    import rostest

    rostest.rosrun("test_mule_bridge", "test_bridge", TestBridge)
